services:

  myapp:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
     - ../src:/app/src
      - ../node_modules:/app/node_modules
    ports:
    - "3000:3000"
    environment:
      - HELLO="hello"
    depends_on:
      - mydb
    networks:
      mynetwork:
        ipv4_address: 172.28.0.3

networks:
  mynetwork:
    external: true